[package]
name = "resmngtest"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/resmngtest.rs"
crate-type = ["staticlib"]

[dependencies]
m3 = { path = "../../libs/rust/m3" }
resmng = { path = "../../libs/rust/resmng" }
