[package]
name = "hashsum"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/hashsum.rs"
crate-type = ["staticlib"]

[dependencies]
m3 = { path = "../../../libs/rust/m3" }
hex = { version="0.4.3", default-features = false, features = ["alloc"] }
